// mcp-kit/apps — registry, factories, schema generators
export { AppRegistry } from './lib/mcp/apps/registry.js'
export { createCreateFormApp, createUpdateFormApp } from './lib/mcp/apps/model-form.js'
export { createListViewApp } from './lib/mcp/apps/list-view.js'
export { createRecordDetailApp } from './lib/mcp/apps/record-detail.js'
export { createSearchViewApp } from './lib/mcp/apps/search-view.js'
export { createAutocompletePickerApp } from './lib/mcp/apps/autocomplete-picker.js'
export { createMultiSelectApp } from './lib/mcp/apps/multi-select.js'
export { generateFormSchema } from './lib/mcp/apps/form-schema.js'
export { generateListSchema } from './lib/mcp/apps/list-schema.js'
export { generateDetailSchema } from './lib/mcp/apps/detail-schema.js'
export { SelectionStore } from './lib/mcp/apps/selection-store.js'
export { createSelectionTools } from './lib/mcp/apps/selection-tools.js'
export { humanize, pluralize } from './lib/mcp/apps/helpers.js'
